GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZnJlZG8iLCJpZCI6IjYxZGVmZDJlYzYyOWI5OWM2MDMwMDhkMyIsImlhdCI6MTY0MjAwMzg3Nn0.hx6GJoEfI6uOib8_TOCi6JAYe1YIk6qv3VcvopZXiN0

{
  "title": "Hello World",
  "author": "Mr Myself",
  "url": "http://localhost:3003",
  "likes": 4
}

###
GET http://localhost:3001/api/blogs/61938304d0a74b2e93cdb362

###
DELETE http://localhost:3001/api/blogs/61df0212378ff44e562082af
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZnJlZG8iLCJpZCI6IjYxZGVmZDJlYzYyOWI5OWM2MDMwMDhkMyIsImlhdCI6MTY0MjAwMzg3Nn0.hx6GJoEfI6uOib8_TOCi6JAYe1YIk6qv3VcvopZXiN0
